#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

# Check for no go files
if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

PASS=true

# Check for formatting issues
for FILE in $STAGED_GO_FILES
do
  go fmt "$FILE"
  if [[ -n $(git diff "$FILE") ]]; then
    echo "\033[31m\t[ERROR] go fmt failed for $FILE\033[0m"
    PASS=false
  fi
done

if ! $PASS; then
  echo "\033[31mCOMMIT FAILED:\033[0m Your commit contains files that should be passed through go fmt. Please run go fmt for these files and commit again."
  exit 1
else
  exit 0
fi